### ISSUE TITLE
Warning on test calculate-staking-apr

### ISSUE THREAD

**Issue by jojoharu** [alpaca-finance/alpaca-sdk-example#5]
Hello,

I try to run an example with command "yarn example:calculate-staking-apr".
I got warning and error message. So, I'm not sure it is normal or I just set wrong config to run.

config address not found, path: Exchanges,Pancakeswap,LpTokens,18
config StrategyPartialCloseLiquidate not found, path: Vaults,0,workers,12,strategies
config StrategyPartialCloseMinimizeTrading not found, path: Vaults,0,workers,12,strategies
config StrategyPartialCloseLiquidate not found, path: Vaults,0,workers,13,strategies
config StrategyPartialCloseMinimizeTrading not found, path: Vaults,0,workers,13,strategies
config StrategyPartialCloseLiquidate not found, path: Vaults,0,workers,17,strategies
config StrategyPartialCloseMinimizeTrading not found, path: Vaults,0,workers,17,strategies
config StrategyPartialCloseLiquidate not found, path: Vaults,0,workers,18,strategies
config StrategyPartialCloseMinimizeTrading not found, path: Vaults,0,workers,18,strategies
config StrategyPartialCloseLiquidate not found, path: Vaults,2,workers,3,strategies
config StrategyPartialCloseMinimizeTrading not found, path: Vaults,2,workers,3,strategies
Warning: 0x2170ed0880ac9a755fd29b2688956bd959f933f8 is not checksummed.
Warning: 0x55d398326f99059ff775485246999027b3197955 is not checksummed.
Warning: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c is not checksummed.
Warning: 0x14016e85a25aeb13065688cafb43044c2ef86784 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x55d398326f99059ff775485246999027b3197955 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x14016e85a25aeb13065688cafb43044c2ef86784 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x2170ed0880ac9a755fd29b2688956bd959f933f8 is not checksummed.
Warning: 0x14016e85a25aeb13065688cafb43044c2ef86784 is not checksummed.
Warning: 0x55d398326f99059ff775485246999027b3197955 is not checksummed.
Warning: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c is not checksummed.
Warning: 0x2170ed0880ac9a755fd29b2688956bd959f933f8 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x14016e85a25aeb13065688cafb43044c2ef86784 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x7130d2a12b9bcbfae4f2634d864a1ee1ce3ead9c is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x55d398326f99059ff775485246999027b3197955 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0xe9e7cea3dedca5984780bafc599bd69add087d56 is not checksummed.
Warning: 0x2170ed0880ac9a755fd29b2688956bd959f933f8 is not checksummed.
Staking Pool: ALPACA Interest Bearing Staking APR: 11.6101137220529408
Staking Pool: BNB Interest Bearing Staking APR: 0.5519616313605225
Staking Pool: BUSD Interest Bearing Staking APR: 0.5063730737650522
Staking Pool: USDT Interest Bearing Staking APR: 0.5220164340110307
Staking Pool: TUSD Interest Bearing Staking APR: 0.6474822433803555
Staking Pool: BTCB Interest Bearing Staking APR: 1.0451876021626386
Staking Pool: ETH Interest Bearing Staking APR: 0.7132760646530357
Done in 20.54s.

**Comment by almost-llamas** [comment]
Try set an `ENV=prod` on a `.env` file, this would help you getting rid the config warning lines. However, the checksummed warning is from the dependency, which we have no quick hack to avoid.
